name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t a-neuk-react:latest .

      # Tag the Docker image
      - name: Tag Docker Image
        run: docker tag a-neuk-react:latest minseok128/a-neuk-react:release1


      # Push the Docker image
      - name: Push Docker Image to Docker Hub
        run: |
          docker push minseok128/a-neuk-react:release1
